name: 'Auto Assign Reviewers and Assignees'

on:
  pull_request:
    types:
      - opened

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Assign Reviewers and Assignees
        uses: kentaro-m/auto-assign-action@v2
        with:
          addReviewers: true
          addAssignees: true
          reviewers: |
            ykybkoft
            haumbin
            dy6379
            HyunBaeL
            rukadeveloper
          numberOfReviewers: 0
          numberOfAssignees: 1
          skipKeywords: |
            wip